---
- name: installing tomcat on remote servers and confuguring changes
  hosts: all
  become: yes
  tasks:
    - name: Downloading tomcat from dlcdn
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.18/bin/apache-tomcat-11.0.18.tar.gz"
        dest: "/root/"

    - name: untar the apache file
      command: tar -zxvf apache-tomcat-11.0.18.tar.gz

    - name: renaming the apache file
      command: mv apache-tomcat-11.0.18 tomcat

    - name: installing the latest available JAVA
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: setting the roles in tomcat-users.xml file
      template:
        src: tomcat-users.xml
        dest: /root/tomcat/conf/tomcat-users.xml

    - name: deleting two lines in context.xml
      template:
        src: context.xml
        dest: /root/tomcat/webapps/manager/META-INF/context.xml

    - name: creating tomcat systemd service file
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Server
          After=network.target

          [Service]
          User=root
          Group=root
          Type=forking
          Environment="JAVA_HOME=/usr/lib/jvm/jre"
          Environment="CATALINA_HOME=/root/tomcat"
          ExecStart=/root/tomcat/bin/startup.sh
          ExecStop=/root/tomcat/bin/shutdown.sh
          Restart=on-failure

          [install]
          WantedBy=muliti-user.target
    - name: Reload systemd
      systemd:
        daemon_reload: yes
    - name: start tomcat service
      service:
        name: tomcat
        state: started
        enabled: yes
