variable "vpc_id" {}
variable "public_subnet_name1" {}
variable "tf_public_subnet_cidr1" {}
variable "public_az1" {}
variable "private_az1" {}
variable "public_subnet_name2" {}
variable "tf_public_subnet_cidr2" {}
variable "public_az2" {}
variable "private_subnet_name1" {}
variable "tf_private_subnet_cidr1" {}
variable "private_subnet_name2" {}
variable "tf_private_subnet_cidr2" {}
variable "private_az2" {}
